language: php
php:
- 7.2
- 7.3
- 7.4
env:
  matrix:
  - LARAVEL_VERSION=5.8.*
  - LARAVEL_VERSION=6.*
  - LARAVEL_VERSION=7.*
  global:
    secure: fsi7vyL5yRvLcAvdOV6fT4rNeE7Z9LostWLFFRwJ0R31ECv5DsJFpcuxyjU7PSyKHjKBzYPHoHE8umM6ri69gshwR3/4Rvi4CZQbhXnsSVRBP/2PsBflIPULl9LoDP7QJZuCuhl3xF1BQ/NwlyiKqENWcN+BGJvInuof+KpYOZEgg4ggCXKYAy9V1xGZLUJwMemsKUdv59lJf7Qeo/kG0hZbQfA5Rwm4wdY7Um5o1uUiF57CQX4hxVN1ggnm9igFDOBf+BgH8WljaHLmOsFZcwLIl8dTDfHsh3dtT6ZfP+quv25k+aLlkPJMr30c6e+w/c4NFnKHyzy7MMjFL5f5RWUXhtoDuQ/F/P33FU3f0Ww45aJXkHtH1KS505qSUPftNzvaEPmU+1577bjhYPd4gFB6+5/bUEiqDBgKcriUAhG/mNrIEIKSdG74wd6A7ElJdja23EKxlot4RGc8mHVjovG9ht5N1XT07u+RhLJOqoqsllLSrX/a4pMOBwjWfiZ8rWLx2eZenEd68hVjztQ89NvGWfLQqg85/gjsjxjS5cajZWuF6asafqUiq2zFCCk0w1EDQxqBYFRt1wTZ2qRNaU6U+OW5KCu9C4Ty6g3lWVni7N/pAKwHOIdSWOaHmKshquJUcDc7Bt1UWwL7SSsvSqVjQiMGHL0wfkVkDdgC7tU=
matrix:
  fast_finish: true
before_script:
- travis_retry composer self-update
- travis_retry composer install --prefer-source --no-interaction
- if [ "$LARAVEL_VERSION" != "" ]; then composer require --dev "laravel/laravel:${LARAVEL_VERSION}"
  --no-update; fi;
- if [ "$LARAVEL_VERSION" == "6.*" ]; then composer require --dev "orchestra/testbench:4.*"
  --no-update; fi;
- if [ "$LARAVEL_VERSION" == "5.8.*" ]; then composer require --dev "orchestra/testbench:3.8.*"
  --no-update; fi;
- composer update
script:
- vendor/bin/phpunit
